### ISSUE TITLE
Sample Data SA1 Code Mismatch

### ISSUE THREAD

**Issue by ryn-trnr** [IGEE-IHVI/iHVI-app#1]
In the recently uploaded sample census data, the SA1_CODE21 uses the 7 digit code, whereas the outputs of the iGEE tool use the 11 digit code. The differences between the codes are described at the bottom this [ABS page](https://www.abs.gov.au/ausstats/abs@.nsf/Lookup/by%20Subject/1270.0.55.001~July%202016~Main%20Features~Statistical%20Area%20Level%201%20(SA1)~10013) 

I suggest either updating the sample data with the more recent 11 digit code for each SA1, or modifying the iGEE tool to also output the 7 digit code for each SA1. Either one of this updates is necessary because at the moment, if you use the provided sample data but generate your own iGEE outputs, they are incompatible because the SA1 codes cannot match.

The sample census data is a great idea because I'm finding it very tricky to generate my own census data from ABS so I would recommend the first solution if possible.

**Comment by SpatialSun** [comment]
Hi shinjita and Kaige, Wenhui,Can you please check Ryan’s comments?Thanks Chayn On 11 Sep 2024, at 11:39, Ryan Turner ***@***.***> wrote:﻿
In the recently uploaded sample census data, the SA1_CODE21 uses the 7 digit code, whereas the outputs of the iGEE tool use the 11 digit code. The differences between the codes are described at the bottom this page ***@***.***/Lookup/by%20Subject/1270.0.55.001~July%202016~Main%20Features~Statistical%20Area%20Level%201%20(SA1)~10013
I suggest either updating the sample data with the more recent 11 digit code for each SA1, or modifying the iGEE tool to also output the 7 digit code for each SA1. Either one of this updates is necessary because at the moment, if you use the provided sample data but generate your own iGEE outputs, they are incompatible because the SA1 codes cannot match.
The sample census data is a great idea because I'm finding it very tricky to generate my own census data from ABS so I would recommend the first solution if possible.

**Comment by SpatialSun** [comment]
RMIT Classification: Trusted

Hi @***@***.***>,

The tool has been updated. Can you please check on your end and let us know if the issue still exists?

Thanks
________________________________

**Comment by ryn-trnr** [comment]
Yes, the issue has been solved. Thank you for updating the sample data to use the 11 digit SA1 code. However, the file headers needed to be renamed, so I did that and now in this form they are directly compatible with outputs of the iGEE tool. I'm attaching the .csv files here for reference. Thanks for your help!

[Education Level.csv](https://github.com/user-attachments/files/17021535/Education.Level.csv)
[Income Level.csv](https://github.com/user-attachments/files/17021536/Income.Level.csv)
[Population Density.csv](https://github.com/user-attachments/files/17021537/Population.Density.csv)
[Population Need Care.csv](https://github.com/user-attachments/files/17021538/Population.Need.Care.csv)
[Age 4-.csv](https://github.com/user-attachments/files/17021539/Age.4-.csv)
[Age 65+.csv](https://github.com/user-attachments/files/17021540/Age.65%2B.csv)
